name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker build -f Dockerfile.deploy -t jorelosorio/spellingcorrector:${{ github.event.release.tag_name }} -t jorelosorio/spellingcorrector:latest .

      - uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker images ${{ github.event.release.tag_name }}
        run: docker push --all-tags ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
