name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: ["1.16.x", "1.17.x"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - run: go install github.com/jandelgado/gcov2lcov@latest

      - name: Create a temp directory to store test data
        run: mkdir tmp

      - name: Create the coverage directory
        run: mkdir coverage

      - name: Run tests
        run: go test -race -covermode atomic -coverprofile=./coverage/coverprofile.out
      
      - run: gcov2lcov -infile=./coverage/coverprofile.out -outfile=./coverage/lcov.info

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-go-${{ matrix.go }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true