name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - run: go test -covermode atomic -coverprofile=profile.cov